[package]
name = "reversi_core"
version.workspace = true
edition.workspace = true

[dependencies]
aligned-vec = "0.6.4"
byteorder = "1.5.0"
lock_api = "0.4.13"
num_cpus = "1.17.0"
rand = "0.9.1"
rapidhash = "2.0.2"
zstd = "0.13.3"
