[package]
name = "ffotest"
version.workspace = true
edition.workspace = true

[dependencies]
clap = { version = "4", features = ["derive"] }
colored = "3"
num-format = "0.4"

reversi-core = { path = "../reversi-core" }
