[package]
name = "ffotest"
version.workspace = true
edition.workspace = true

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
colored = "3.0.0"
num-format = "0.4.4"

reversi-core = { path = "../reversi-core" }
