[package]
name = "time-debug"
version.workspace = true
edition.workspace = true

[[bin]]
name = "time-debug"
path = "src/main.rs"

[dependencies]
reversi-core = { path = "../reversi-core" }
clap = { version = "4", features = ["derive"] }
colored = "3"
